# Generated by Django 6.0.5 on 2026-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.FloatField(default=1.0),
        ),
    ]
