# Generated by Django 6.0.5 on 2026-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
