# Generated by Django 6.0.5 on 2026-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_task_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="target",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
