# Generated by Django 6.0.5 on 2026-08-10 10:59

import pyobs.robotic.observation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_observation_state_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="obsnum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        pyobs.robotic.observation.ObservationState["PENDING"],
                        pyobs.robotic.observation.ObservationState["PENDING"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["COMPLETED"],
                        pyobs.robotic.observation.ObservationState["COMPLETED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["IN_PROGRESS"],
                        pyobs.robotic.observation.ObservationState["IN_PROGRESS"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["ABORTED"],
                        pyobs.robotic.observation.ObservationState["ABORTED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["CANCELED"],
                        pyobs.robotic.observation.ObservationState["CANCELED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["FAILED"],
                        pyobs.robotic.observation.ObservationState["FAILED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["WINDOW_EXPIRED"],
                        pyobs.robotic.observation.ObservationState["WINDOW_EXPIRED"],
                    ),
                ],
                default=pyobs.robotic.observation.ObservationState["PENDING"],
                max_length=15,
            ),
        ),
    ]
