# Generated by Django 6.1 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_observation_obsnum_alter_observation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Public projects are accessible to every authenticated user; private projects only to their members.",
            ),
        ),
    ]
