# Generated by Django 6.1 on 2026-09-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4, unique=True)),
                ("pixel_size_um", models.FloatField(blank=True, null=True)),
                ("sensor_width_px", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sensor_height_px",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "roi_min_width_px",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "roi_min_height_px",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("roi_step_px", models.PositiveIntegerField(blank=True, null=True)),
                ("exposure_time_min_s", models.FloatField(blank=True, null=True)),
                ("exposure_time_max_s", models.FloatField(blank=True, null=True)),
                ("image_types", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["module_name"],
            },
        ),
        migrations.CreateModel(
            name="FilterWheelCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("filter_change_time_s", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_wheels",
                        to="instruments.cameracapability",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DomeCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rotate_rate_deg_per_s", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dome",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cameracapability",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cameras",
                to="instruments.instrument",
            ),
        ),
        migrations.CreateModel(
            name="TelescopeCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aperture_mm", models.FloatField(blank=True, null=True)),
                ("focal_length_mm", models.FloatField(blank=True, null=True)),
                ("mount_type", models.CharField(blank=True, max_length=255)),
                ("slew_rate_deg_per_s", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telescope",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinningOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                ("readout_time_s", models.FloatField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binnings",
                        to="instruments.cameracapability",
                    ),
                ),
            ],
            options={
                "ordering": ["x", "y"],
                "unique_together": {("camera", "x", "y")},
            },
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "filter_wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="instruments.filterwheelcapability",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "unique_together": {("filter_wheel", "name")},
            },
        ),
    ]
