# Generated by Django 6.1 on 2026-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0002_instrument_config_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="binningoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="filter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
