# Generated by Django 6.1 on 2026-09-02 07:28, then hand-edited to backfill module_name from
# the old Instrument.module_name losslessly instead of blanking every existing row -- see
# backfill_module_names below.

from django.db import migrations, models


def backfill_module_names(apps, schema_editor):
    """Carry the old Instrument.module_name forward to the new per-device fields.

    Telescope/dome are 1:1 with an Instrument, so their module_name is always recoverable --
    it's the same value Instrument.module_name held. A camera has no recoverable value of its
    own; the old convention (per #133's test fixtures) was one camera per instrument sharing the
    instrument's module_name, so that case is backfilled the same way. An instrument with more
    than one camera (the science+guide case #139 exists for) has no way to auto-disambiguate,
    so this raises instead of guessing -- silently blanking or duplicating a module_name would be
    worse than a migration that stops and asks for manual input.
    """
    Instrument = apps.get_model("instruments", "Instrument")
    TelescopeCapability = apps.get_model("instruments", "TelescopeCapability")
    DomeCapability = apps.get_model("instruments", "DomeCapability")
    CameraCapability = apps.get_model("instruments", "CameraCapability")

    ambiguous = []
    for instrument in Instrument.objects.all():
        TelescopeCapability.objects.filter(instrument=instrument).update(
            module_name=instrument.module_name
        )
        DomeCapability.objects.filter(instrument=instrument).update(
            module_name=instrument.module_name
        )

        cameras = list(CameraCapability.objects.filter(instrument=instrument))
        if len(cameras) == 1:
            cameras[0].module_name = instrument.module_name
            cameras[0].save(update_fields=["module_name"])
        elif len(cameras) > 1:
            ambiguous.append(
                (instrument.pk, instrument.module_name, [c.code for c in cameras])
            )

    if ambiguous:
        details = "\n".join(
            f"  - instrument #{pk} (was module_name={old_name!r}): cameras {codes!r}"
            for pk, old_name, codes in ambiguous
        )
        raise RuntimeError(
            "Cannot auto-backfill CameraCapability.module_name: the following instruments have "
            "more than one camera, so there's no single old Instrument.module_name to reuse. Set "
            "each camera's module_name by hand (e.g. via the admin, before re-running this "
            "migration), then re-run `manage.py migrate`:\n" + details
        )


def noop_reverse(apps, schema_editor):
    # The old Instrument.module_name doesn't come back with data on reverse -- nothing sensible
    # to restore it from.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_binningoption_updated_at_filter_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["display_name"]},
        ),
        # Added nullable first so backfill_module_names has somewhere to write existing rows'
        # values into before the NOT NULL constraint is enforced below.
        migrations.AddField(
            model_name="cameracapability",
            name="module_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="domecapability",
            name="module_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="telescopecapability",
            name="module_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_module_names, noop_reverse),
        migrations.RemoveField(
            model_name="instrument",
            name="module_name",
        ),
        migrations.AlterField(
            model_name="cameracapability",
            name="module_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="domecapability",
            name="module_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="telescopecapability",
            name="module_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
