# Generated by Django 6.1 on 2026-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_binningoption_updated_at_filter_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["display_name"]},
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="module_name",
        ),
        migrations.AddField(
            model_name="cameracapability",
            name="module_name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="domecapability",
            name="module_name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telescopecapability",
            name="module_name",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
