# Generated by Django 6.1 on 2026-09-02, hand-written to match the shape of
# 0004_module_name_per_device_capability.py -- adds the same module-name identity key to
# FilterWheelCapability so ImagingScript.filters (a module name) can be matched directly, the
# way ImagingScript.camera/.telescope already match CameraCapability/TelescopeCapability.
#
# Unlike Camera/Telescope/Dome, this is nullable: a filter wheel isn't always its own
# addressable module (some cameras expose filter selection through the same module as the
# camera itself), so "unknown module" is a valid, common state here, not a data gap to force a
# backfill decision over.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0004_module_name_per_device_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterwheelcapability",
            name="module_name",
            field=models.CharField(max_length=255, null=True, blank=True, unique=True),
        ),
    ]
