# Generated by Django 6.1 on 2026-09-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0005_filterwheelcapability_module_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoofCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=255, unique=True)),
                ("open_close_time_s", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roof",
                        to="instruments.instrument",
                    ),
                ),
            ],
        ),
    ]
