# Generated by Django 6.1 on 2026-09-04 12:01

from django.db import migrations, models


def reject_blank_module_names(apps, schema_editor):
    """Belt-and-braces guard ahead of the NOT NULL AlterField below: NULL rows would fail that
    step outright, but a pre-#142 `blank=True` row (or a direct ORM write bypassing
    full_clean()) could hold `""` instead, which NOT NULL doesn't catch and which would silently
    carry the same unreachable-row bug forward under a new disguise. Fail loudly instead -- a
    human needs to give the row a real module_name (or the camera's own, if it's an integrated
    wheel) before this migration can proceed.
    """
    FilterWheelCapability = apps.get_model("instruments", "FilterWheelCapability")
    blank = FilterWheelCapability.objects.filter(module_name="")
    if blank.exists():
        names = ", ".join(str(pk) for pk in blank.values_list("pk", flat=True))
        raise RuntimeError(
            f"FilterWheelCapability row(s) with pk {names} have an empty module_name -- "
            "give them a real one (or the camera's own module_name, if integrated) before "
            "migrating."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0007_roofcapability_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameracapability",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cameracapability",
            name="sensor_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="filterwheelcapability",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(reject_blank_module_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="filterwheelcapability",
            name="module_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
