# Generated by Django 6.1 on 2026-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0007_roofcapability_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameracapability",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cameracapability",
            name="sensor_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="filterwheelcapability",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="filterwheelcapability",
            name="module_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
