"""
Django settings for pyobs_robotic_backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "foo")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a comma between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]'
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# same as DJANGO_ALLOWED_HOSTS
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost").split(
    ","
)

# 'CORS_ALLOWED_ORIGINS' should be a single string of origins (scheme + host [+ port])
# separated by commas, e.g. for a frontend served from a different host/port than the API:
#   CORS_ALLOWED_ORIGINS=http://localhost:8097,https://your.domain.com
CORS_ALLOWED_ORIGINS = [
    origin
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin
]

# The bundled nginx.conf.example sets "X-Forwarded-Proto: $scheme" and is the
# only public entry point (gunicorn itself is not published), so it's safe to
# trust this header to tell Django the original request was HTTPS. Without
# this, request.build_absolute_uri() (e.g. DRF's pagination "next"/"previous"
# links) would always use "http://", causing mixed-content errors behind a
# TLS-terminating proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Django's SecurityMiddleware sends "Cross-Origin-Opener-Policy: same-origin" by
# default, but browsers only honor COOP over HTTPS (or localhost) - served over
# plain HTTP it's just a no-op that logs a console warning. Deployments that
# terminate TLS can leave this at its default; HTTP-only deployments can set
# SECURE_CROSS_ORIGIN_OPENER_POLICY=none to silence the warning.
_coop = os.environ.get("SECURE_CROSS_ORIGIN_OPENER_POLICY", "same-origin")
SECURE_CROSS_ORIGIN_OPENER_POLICY = None if _coop.lower() == "none" else _coop

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "pyobs_robotic_backend.api",
]

FRONTEND_ENABLED = os.environ.get("ENABLE_FRONTEND", "0") == "1"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pyobs_robotic_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pyobs_robotic_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "amqp://")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "rpc://")
CELERY_TIMEZONE = "UTC"
CELERY_TASK_QUEUES = {
    "celery": {
        "exchange": "celery",
        "routing_key": "celery",
        "queue_arguments": {},
        "durable": True,  # persist queue across broker restarts
        "auto_delete": False,
    }
}
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_QUEUE_DURABLE = True  # for newer Celery versions

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = "static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", os.path.join(BASE_DIR, "static"))

SITE_LATITUDE = (
    float(os.environ["SITE_LATITUDE"]) if os.environ.get("SITE_LATITUDE") else None
)
SITE_LONGITUDE = (
    float(os.environ["SITE_LONGITUDE"]) if os.environ.get("SITE_LONGITUDE") else None
)
SITE_ELEVATION = (
    float(os.environ["SITE_ELEVATION"]) if os.environ.get("SITE_ELEVATION") else None
)

# Default constraints/merits pre-filled when creating a new task in the
# web frontend.  Set via JSON env vars, e.g.:
#   DEFAULT_CONSTRAINTS='[{"class":"pyobs.robotic.scheduler.constraints.AirmassConstraint","max_airmass":2.0}]'
#   DEFAULT_MERITS='[{"class":"pyobs.robotic.scheduler.merits.ConstantMerit","value":1.0}]'
import json as _json

DEFAULT_CONSTRAINTS = _json.loads(os.environ.get("DEFAULT_CONSTRAINTS") or "[]")
DEFAULT_MERITS = _json.loads(os.environ.get("DEFAULT_MERITS") or "[]")

try:
    from .local_settings import *
except ImportError:
    pass

# local_settings may set these as JSON strings (mirrors the env-var format)
if isinstance(DEFAULT_CONSTRAINTS, str):
    DEFAULT_CONSTRAINTS = _json.loads(DEFAULT_CONSTRAINTS)
if isinstance(DEFAULT_MERITS, str):
    DEFAULT_MERITS = _json.loads(DEFAULT_MERITS)

if FRONTEND_ENABLED:
    if "pyobs_robotic_backend.frontend" not in INSTALLED_APPS:
        INSTALLED_APPS.append("pyobs_robotic_backend.frontend")
    LOGIN_URL = "frontend:login"
    LOGIN_REDIRECT_URL = "frontend:dashboard"
    LOGOUT_REDIRECT_URL = "frontend:login"
