# Generated by Django 6.0.5 on 2026-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="constraint",
            options={"ordering": ["task", "type"]},
        ),
        migrations.AlterModelOptions(
            name="merit",
            options={"ordering": ["task", "type"]},
        ),
        migrations.AlterModelOptions(
            name="observation",
            options={"ordering": ["start"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="target",
            options={"ordering": ["task", "name"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["code"]},
        ),
    ]
