# Generated by Django 6.0.5 on 2026-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_constraint_options_alter_merit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
