# Generated by Django 6.0.5 on 2026-06-17 10:49

import pyobs.robotic.observation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_observation_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="state",
            field=models.CharField(
                choices=[
                    (
                        pyobs.robotic.observation.ObservationState["PENDING"],
                        pyobs.robotic.observation.ObservationState["PENDING"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["COMPLETED"],
                        pyobs.robotic.observation.ObservationState["COMPLETED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["IN_PROGRESS"],
                        pyobs.robotic.observation.ObservationState["IN_PROGRESS"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["ABORTED"],
                        pyobs.robotic.observation.ObservationState["ABORTED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["CANCELED"],
                        pyobs.robotic.observation.ObservationState["CANCELED"],
                    ),
                    (
                        pyobs.robotic.observation.ObservationState["FAILED"],
                        pyobs.robotic.observation.ObservationState["FAILED"],
                    ),
                ],
                default=pyobs.robotic.observation.ObservationState["PENDING"],
                max_length=15,
            ),
        ),
    ]
